### ISSUE TITLE
Take args for repository and ref, instead of using fixed environment variables

### ISSUE THREAD

**Issue by douglasnaphas** [cdk-turnkey/stackname#13]
Stackname could be useful outside of GitHub Actions.

**Comment by douglasnaphas** [comment]
# TODO
- [x] Use CDK v2 in itest.
- [ ] Use OIDC for running itest.
- [ ] Parameterize the printed name of the package, currently hardcoded as `@cdk-turnkey/stackname`.
- [ ] See what I can get out of the Git CLI for org, repo name, and branch.
- [x] Get rid of `shortName`.
